version: '3'

services:
  first-container:
    image: ${image_name}
    
    depends_on: 
      - second-container
    networks:
      - buddy

  second-container:
    image: ${image_name}
    depends_on:
      - third-container
    networks:
      - buddy 

  third-container:
    image: ${image_name}
    restart: always
    networks:
      - buddy  

networks:
  buddy:
    ipam:
      driver: default
      config:
        - subnet: "172.168.238.0/24"
